[build]
  command = "pip install -r requirements.txt && gunicorn -k uvicorn.workers.UvicornWorker app.main:app && alembic revision --autogenerate -m 'generate initial migration' && alembic upgrade head"
