"""add phone number column to user table

Revision ID: de9a9326bd13
Revises: d2e79e721e20
Create Date: 2023-09-03 17:29:32.861861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9a9326bd13'
down_revision: Union[str, None] = 'd2e79e721e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_num', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_num')
    # ### end Alembic commands ###
